version: '3.8'

services:
  servicebridge-api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:80"
      - "5001:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DefaultConnection=Data Source=/app/data/servicebridge.db
    volumes:
      - servicebridge-data:/app/data

volumes:
  servicebridge-data:
